[service]
name = "tetra"
command = "node server/server.js"
description = "Tetra dashboard and API server"

[shared]
TETRA_ENV = "local"

[local]
PORT = "4444"

[dev]
PORT = "4444"
TETRA_ENV = "dev"

[prod]
PORT = "4444"
TETRA_ENV = "prod"
