version: '3'

networks:
  web-network:
    name: web-network
    external: true

volumes:
  grafana-storage:
  prometheus-storage:

services:
  grafana:
    image: grafana/grafana-oss
    environment:
       - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel,grafana-polystat-panel
      # - GF_LOG_LEVEL=debug
    ports:
      - "5000:3000"
    networks:
      - web-network
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: always
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/etc:/etc/prometheus
    restart: always
    networks:
      - web-network

  adapter:
    container_name: adapter
    hostname: mysql_adapter
    restart: always
    build:
      context: ./adapter/
    volumes:
      - ./adapter/app:/app
    working_dir: /app
    ports:
      - 3306:3306
      - 3307:3306
      - 3308:3306
    environment:
      - SSH_KEY=${SSH_KEY}
      - SSH_USER=${SSH_USER}
      - SSH_HOST=${SSH_HOST}
      - LOCAL_PORT=${LOCAL_PORT}
      - REMOTE_HOST=${REMOTE_HOST}
      - REMOTE_PORT=${REMOTE_PORT}
    networks:
      - web-network

    # This would override ENTRYPOINT defined in Dockerfile 
    # entrypoint: /app/entrypoint.sh
